

include ../../makefile.neiku

DIY_INC =

DIY_LIB = 

VPATH = ../../src/neiku/

OUTPUT=proc_test

ALL: $(OUTPUT)

proc_test:proc_test.o cmdline.o

clean:
	rm -f $(OUTPUT) *.o *.a *.so

