
commands_py = `pwd`/commands.py
readme_txt  = `pwd`/readme.txt

all:
	@echo "Usage: make [install | clean]"

clean:
	rm -fv *~

install:
	@echo -e "\e[32;1mfor install ${commands_py}, ${readme_txt} can help you!\e[0m"
