#
# To use it, do:
# ----you makefile----
# include makefile.dir
# 
# DIRS= dir1 dir2
# -------------------
# $ make
# $ make clean
# $ make ACTION=clean
# $ make ACTION=<what you want>

DIRS=

ACTION=

all:
	@for subdir in $(DIRS); \
	do \
		$(MAKE) -C $$subdir $(ACTION); \
	done

clean:
	@for subdir in $(DIRS); \
	do \
		$(MAKE) -C $$subdir clean; \
	done

