

include ../../makefile.neiku

DIY_INC =

DIY_LIB = 

VPATH = ../../src/neiku/

OUTPUT = cmdline_test

ALL: $(OUTPUT)

cmdline_test:cmdline_test.o cmdline.o

clean:
	rm -f $(OUTPUT) *.o *.a *.so *.exe *~

