#!/bin/bash
# vim:ts=4:sw=4:expandtab

############################################################
# NAME
#     mkdd - mkd for directorys
#
# SYNOPSIS
#     mkdd
#     mkdd [ -f makefile ] [ -C directory ]
# 
#     debug=on mkdd ...
#
# AUTHORS
#     neiku project <ku7d@qq.com> 
#
# SEE ALSO
#     mkd
#
# VERSION
#     2015/11/21: 简单封装mkd，实现目录级递归mkd
#
############################################################

# i need mkd
if ! which mkd >/dev/null 2>&1
then
    echo "mkd not found"
    exit 1
fi

# get make directorys
makedirs="`make $* -n -p 2>/dev/null | grep '^DIRS =' | cut -c8-`"
if [ -z "$makedirs" ]
then
    echo "make directorys not found, make args:[$*]" >&2
    exit 1
fi

# get make directory
makedir="`make $* -n -p 2>/dev/null | grep '^CURDIR :=' | tail -n1 | cut -c11-`"
if [ -z "$makedir" ]
then
    echo "make directory not found, make args:[$*]" >&2
    exit 1
fi

# mkd for each directory
for dir in $makedirs
do
    mkd -C $makedir/$dir
done
