#!/bin/bash
# vim:ts=4:sw=4:expandtab

############################################################
# NAME
#     mkr - a toy for run target's restart command
#
# SYNOPSIS
#     mkr
#     mkr [ -f makefile ] [ targets ] ...
# 
#     debug=on mkr ...
#
# AUTHORS
#     neiku project <ku7d@qq.com> 
#
# SEE ALSO
#     mkxrc_commands
#     mkxrc_targets
#     mkxrc_modules
#
# VERSION
#     2015/11/21: 简单封装mkrun，支持重启
#                 命令行或者makefile中OUTPUT定义的target
#     2015/12/03: 支持目录递归查找target
#
############################################################

# i need mkrun
if ! which mkrun >/dev/null 2>&1
then
    mklog error "mkrun not found"
    exit 1
fi

# get make directory
makedir="`make $* -n -p 2>/dev/null | grep '^CURDIR :=' | tail -n1 | cut -c11-`"
if [ -z "$makedir" ] ; then
    mklog error "make directory not found, make args:[$*]"
    exit 1
fi
mklog debug "makedir=$makedir"

# maybe mkr for sub directorys
submakedirs="`make $* -n -p 2>/dev/null | grep '^DIRS =' | tail -n1 | cut -c8-`"
mklog debug "submakedirs=$submakedirs"
if [ -n "$submakedirs" ] ; then
    for subdir in $submakedirs
    do
        mkrdir=""
        if [ "${subdir:0:1}" = "/" ] ; then
            mkrdir="$subdir"
        else
            mkrdir="$makedir/$subdir"
        fi

        pwd="`pwd`"
        echo "mkr: Entering directory '$mkrdir'"
        cd "$mkrdir"
        mkr
        echo "mkr: Leaving directory '$mkrdir'"
        cd "$pwd"
    done
    mklog debug "mkr for directorys end"
    exit 0
fi

# get targets from cmdline
targets="`make $* -n -p 2>/dev/null | grep '^MAKECMDGOALS :=' | cut -c17-`"
if [ -z "$targets" ]
then
    # default targets from OUTPUT var in makefile
    targets="`make $* -n -p 2>/dev/null | grep '^OUTPUT =' | cut -c10-`"
fi
if [ -z "$targets" ]
then
    mklog error "targets not found, make args:[$*]"
    exit 1
fi
mklog debug "targets;[$targets]"

# run target's restart command
mkrun restart $targets
