#!/bin/bash
# vim:ts=4:sw=4:expandtab

############################################################
# NAME
#     mks - a toy for run target's start command
#
# SYNOPSIS
#     mks
#     mks [ -f makefile ] [ targets ] ...
# 
#     debug=on mks ...
#
# AUTHORS
#     neiku project <ku7d@qq.com> 
#
# SEE ALSO
#     mkxrc_commands
#     mkxrc_targets
#     mkxrc_modules
#
# VERSION
#     2015/11/21: 简单封装mkrun，支持启动
#                 命令行或者makefile中OUTPUT定义的target
#     2015/12/03: 支持目录递归查找target
#     2016/02/16: 支持自定义默认target变量名(key => output-name)
#                 (默认使用OUTPUT做为默认target变量名)
#
############################################################

# i need mkrun
if ! which mkrun >/dev/null 2>&1
then
    mklog error "mkrun not found"
    exit 1
fi

# get make directory
makedir="`make $* -n -p 2>/dev/null | grep '^CURDIR :=' | tail -n1 | cut -c11-`"
if [ -z "$makedir" ] ; then
    mklog error "make directory not found, make args:[$*]"
    exit 1
fi
mklog debug "makedir=$makedir"

# maybe mks for sub directorys
submakedirs="`make $* -n -p 2>/dev/null | grep '^DIRS =' | tail -n1 | cut -c8-`"
mklog debug "submakedirs=$submakedirs"
if [ -n "$submakedirs" ] ; then
    for subdir in $submakedirs
    do
        mksdir=""
        if [ "${subdir:0:1}" = "/" ] ; then
            mksdir="$subdir"
        else
            mksdir="$makedir/$subdir"
        fi

        pwd="`pwd`"
        echo "mks: Entering directory '$mksdir'"
        cd "$mksdir"
        mks
        echo "mks: Leaving directory '$mksdir'"
        cd "$pwd"
    done
    mklog debug "mks for directorys end"
    exit 0
fi

# get targets from cmdline
targets="`make $* -n -p 2>/dev/null | grep '^MAKECMDGOALS :=' | cut -c17-`"
if [ -z "$targets" ]
then
    # default targets from $output var in makefile
    output="`mkm get config output-name OUTPUT`"
    length="$((${#output} + 4))"
    targets="`make $* -n -p 2>/dev/null | grep "^$output =" | cut -c$length-`"
    if [ -z "$targets" ]
    then
        mklog error "targets not found, make args:[$*]," \
                    "output-name:[$output], length:[$length]"
        exit 1
    fi
fi
mklog debug "targets:[$targets]"

# run target's start command
mkrun start $targets
