

include ../../makefile.neiku

DIY_INC = -I../../include/ \

DIY_LIB = -lneiku

VPATH = 

OUTPUT = test_log

ALL: $(OUTPUT)

test_log:test_log.o

clean:
	rm -f $(OUTPUT) *.o *.a *.so

