#!/usr/bin/env bash
# vim:ts=4:sw=4:expandtab

############################################################
# NAME
#     mp-log - tool for output log
#
# SYNOPSIS
#     mp-log error|normal|debug message ...
#
# AUTHORS
#     neiku project <ku7d@qq.com> 
#
# VERSION
#     copy from mklog (MKX)
#
############################################################

function normaltext()  { echo -n  "$*"; } 
function redtext()     { echo -en "\e[31;1m$*\e[0m"; }
function greentext()   { echo -en "\e[32;1m$*\e[0m"; }
function pinktext()    { echo -en "\e[35;1m$*\e[0m"; }
function yellowtext()  { echo -en "\e[33;1m$*\e[0m"; }

if [ $# -lt 2 ]
then
    echo "usage: $0 error|normal|debug message ..." >&2
    exit 1
fi

type="$1"
shift 1

if [ "$type" = "error" ]
then
    echo "`redtext $*`" >&2
elif [ "$type" = "normal" ]
then
    echo "`greentext $*`"
elif [ "$type" = "tip" ]
then
    echo -n "`pinktext "$*"`"
elif [ "$type" = "debug" ]
then
    if [ -n "$debug" ] ; then echo "`yellowtext "$*"`" >&2; fi
fi
