

include ../../makefile.neiku

DIY_INC = -I../../include/ \

DIY_LIB = -lneiku

VPATH = 

OUTPUT = json_test

ALL: $(OUTPUT)

json_test:json_test.o

clean:
	rm -f $(OUTPUT) *.o *.a *.so

