

include ../../makefile.neiku

DIY_INC =

DIY_LIB = 

VPATH = ../../src/neiku/

OUTPUT = time_test

ALL: $(OUTPUT)

time_test: time_test.o time.o

clean:
	rm -f $(OUTPUT) *.o *.a *.so *.exe *~

