

include ../../makefile.neiku

DIY_INC = -I../../include/ \

DIY_LIB =

VPATH = 

OUTPUT = test_json_serialize

ALL: $(OUTPUT)

test_json_serialize:test_json_serialize.o

clean:
	rm -f $(OUTPUT) *.o *.a *.so

