# vim:ts=4:sw=4:expandtab

include ../makefile.dir

DIRS = singleton \
       charset \
       json \
       log \
       md5 \
       cmdline \
       proc \
       serialize \
       cgx \
       cs \
