

include ../../makefile.neiku

DIY_INC = -I../../include/ \

DIY_LIB = -lneiku

VPATH =

OUTPUT = charset_test

ALL: $(OUTPUT)

charset_test: charset_test.o

clean:
	rm -f $(OUTPUT) *.o *.a *.so

